Repository bcgsc/mavis, pull requests merged in 2018-03, with the labels that each got.

#69 Pairing with useq and alignment_rank rename
  mavis/align.py
  mavis/bam/read.py
  mavis/blat.py
  mavis/constants.py
  mavis/pairing/pairing.py
  mavis/summary/main.py
  mavis/validate/base.py
  mavis/validate/call.py
  mavis/validate/main.py
  tests/integration/test_align.py
  tests/integration/test_pairing.py
  tests/integration/test_validate_call.py
Labels: enhancement

#73 Configurable parameter simplification
  mavis/align.py
  mavis/assemble.py
  mavis/bam/read.py
  mavis/blat.py
  mavis/breakpoint.py
  mavis/checker.py
  mavis/main.py
  mavis/pairing/constants.py
  mavis/pairing/pairing.py
  mavis/submit.py
  mavis/summary/main.py
  mavis/summary/summary.py
  mavis/validate/base.py
  mavis/validate/call.py
  mavis/validate/constants.py
  tests/end_to_end/data/bwa_pipeline_config.cfg
  tests/end_to_end/data/clean_pipeline_config.cfg
  tests/end_to_end/data/pipeline_config.cfg
  tests/integration/data/large_assembly.txt
  tests/integration/test_align.py
  tests/integration/test_assemble.py
  tests/integration/test_bam.py
  tests/integration/test_blat.py
  tests/integration/test_checker.py
  tests/integration/test_pairing.py
  tests/integration/test_validate.py
  tests/integration/test_validate_call.py
  tests/unit/test_assemble.py
  tests/unit/test_breakpoint.py
  tests/unit/test_submit.py
Labels: enhancement

#80 doc Example and Config option tests
  docs/source/examples.rst
  docs/source/glossary.rst
  docs/source/index.rst
  docs/source/pipeline.rst
  docs/source/tools_supported.rst
  mavis/assemble.py
  mavis/bam/read.py
  mavis/config.py
  mavis/constants.py
  mavis/validate/base.py
  mavis/validate/call.py
  mavis/validate/constants.py
  tests/end_to_end/data/pipeline_config.cfg
  tests/end_to_end/test_config.py
  tests/end_to_end/test_full_pipeline.py
  tests/integration/test_assemble.py
  tests/unit/test_bam.py
Labels: documentation, enhancement

#82 scope review 1.7.0
  docs/source/examples.rst
  docs/source/glossary.rst
  docs/source/index.rst
  docs/source/pipeline.rst
  docs/source/tools_supported.rst
  mavis/align.py
  mavis/assemble.py
  mavis/bam/read.py
  mavis/blat.py
  mavis/breakpoint.py
  mavis/checker.py
  mavis/config.py
  mavis/constants.py
  mavis/main.py
  mavis/pairing/constants.py
  mavis/pairing/pairing.py
  mavis/submit.py
  mavis/summary/main.py
  mavis/summary/summary.py
  mavis/validate/base.py
  mavis/validate/call.py
  mavis/validate/constants.py
  mavis/validate/main.py
  setup.py
  tests/end_to_end/data/bwa_pipeline_config.cfg
  tests/end_to_end/data/clean_pipeline_config.cfg
  tests/end_to_end/data/pipeline_config.cfg
  tests/end_to_end/test_config.py
  tests/end_to_end/test_convert.py
  tests/end_to_end/test_full_pipeline.py
  tests/end_to_end/test_help.py
  tests/end_to_end/test_overlay.py
  tests/end_to_end/test_pairing.py
  tests/integration/__init__.py
  tests/integration/data/large_assembly.txt
  tests/integration/test_align.py
  tests/integration/test_assemble.py
  tests/integration/test_bam.py
  tests/integration/test_blat.py
  tests/integration/test_checker.py
  tests/integration/test_pairing.py
  tests/integration/test_validate.py
  tests/integration/test_validate_call.py
  tests/unit/test_assemble.py
  tests/unit/test_bam.py
  tests/unit/test_breakpoint.py
  tests/unit/test_submit.py
Labels: bug, documentation, enhancement

#84 #83 added updates to the checker
  mavis/checker.py
  mavis/main.py
  tests/integration/test_checker.py
Labels: enhancement

#87 #86: catching the empty file error
  mavis/blat.py
  setup.py
Labels: bug

#89 v1.7.1
  README.md
  docs/source/about.rst
  mavis/bam/read.py
  mavis/blat.py
  mavis/checker.py
  mavis/main.py
  mavis/pairing/constants.py
  mavis/validate/main.py
  setup.py
  tests/end_to_end/test_full_pipeline.py
  tests/integration/config.py
  tests/integration/test_bam.py
  tests/integration/test_checker.py
  tests/integration/test_mains.py
Labels: bug, enhancement
