Repository bcgsc/mavis, pull requests merged in 2020-07, with the labels that each got.

#217 Bugfix/issue 213 bnd non trans
  mavis/tools/constants.py
  mavis/tools/vcf.py
  tests/data/manta_events.vcf
  tests/end_to_end/test_convert.py
  tests/unit/test_tool.py
Labels: bug

#220 Feature/issue 216 GitHub actions
  .github/workflows/build.yml
  .github/workflows/publish.yml
  .travis.yml
  README.md
  codecov.yml
  setup.py
  tests/test_style.py
  tests/unit/test_assemble.py
  tox.ini
Labels: devops, refactor

#221 Update issue templates
  .github/ISSUE_TEMPLATE.md
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: documentation

#207 generate_ensembl_json.py
  docs/inputs/reference.md
  setup.py
  tools/generate_ensembl_json.pl
  tools/generate_ensembl_json.py
Labels: documentation, enhancement, reference files
