Repository bcgsc/mavis, pull requests merged in 2022-11, with the labels that each got.

#337 Bugfix to Summary module clustering output
  .github/workflows/build.yml
  setup.cfg
  src/mavis/summary/summary.py
  tests/data/mock_dgv_annotation.txt
  tests/test_mavis/summary/test_summary.py
Labels: bug

#340 Ignore type-checking only lines in coverage report
  .coveragerc
Labels: devops

#336 Change support for MAVIS input in summary module
  docs/outputs/columns.md
  src/mavis/annotate/file_io.py
  src/mavis/constants.py
  src/mavis/pairing/pairing.py
  src/mavis/summary/main.py
  src/mavis/summary/summary.py
  src/tools/convert_dgv.py
  tests/data/mock_dgv_annotation.tab
  tests/data/mock_dgv_annotation_malformed.tab
  tests/data/mock_dgv_annotation_mavis.tab
  tests/data/mock_masking.tab
  tests/full-tutorial.config.json
  tests/mini-tutorial.annotate_only.config.json
  tests/mini-tutorial.config.json
  tests/test_mavis/summary/test_summary.py
  tests/test_mavis/test_util.py
  tests/test_tools/data/dgv_test.tab
  tests/test_tools/data/dgv_test_expected.tab
  tests/test_tools/test_convert_dgv.py
Labels: enhancement

#339 Release/v3.1.0
  .github/workflows/build.yml
  README.md
  docs/background/citations.md
  docs/glossary.md
  docs/inputs/.pages
  docs/inputs/non_python_dependencies.md
  docs/inputs/reference.md
  docs/inputs/support.md
  docs/inputs/sv_callers.md
  setup.cfg
  src/mavis/bam/read.py
  src/mavis/breakpoint.py
  src/mavis/convert/__init__.py
  src/mavis/convert/arriba.py
  src/mavis/convert/constants.py
  src/mavis/convert/straglr.py
  src/mavis/convert/vcf.py
  src/mavis/main.py
  src/mavis/summary/summary.py
  src/mavis/util.py
  src/mavis/validate/align.py
  src/mavis/validate/assemble.py
  src/mavis/validate/base.py
  src/mavis/validate/blat.py
  src/mavis/validate/call.py
  src/mavis/validate/evidence.py
  src/mavis/validate/gather.py
  src/mavis/validate/main.py
  tests/data/mock_dgv_annotation.txt
  tests/data/straglr.bed
  tests/test_mavis/bam/test_bam.py
  tests/test_mavis/bam/test_cigar.py
  tests/test_mavis/convert/test_convert.py
  tests/test_mavis/convert/test_tool.py
  tests/test_mavis/convert/test_tools_vcf.py
  tests/test_mavis/mock.py
  tests/test_mavis/summary/test_summary.py
  tests/test_mavis/test_align.py
  tests/test_mavis/test_args.py
  tests/test_mavis/test_assemble.py
  tests/test_mavis/test_assemble2.py
  tests/test_mavis/test_blat.py
  tests/test_mavis/test_blat2.py
  tests/test_mavis/test_breakpoint.py
  tests/test_mavis/validate/test_call.py
  tests/test_mavis/validate/test_evidence.py
  tests/test_mavis/validate/test_validate2.py
Labels: SV caller, code-style, release

#342 Refactor/enforce isort
  .github/workflows/quick-tests.yml
  .gitignore
  setup.cfg
  src/mavis/annotate/file_io.py
  src/mavis/cluster/__init__.py
  src/mavis/constants.py
  src/mavis/convert/arriba.py
  src/mavis/convert/transabyss.py
  src/mavis/convert/vcf.py
  src/mavis/illustrate/diagram.py
  src/mavis/illustrate/util.py
  src/mavis/summary/summary.py
  src/mavis/validate/align.py
  src/mavis/validate/base.py
  src/tools/calculate_ref_alt_counts.py
  src/tools/convert_annotations_format.py
  src/tools/convert_dgv.py
  tests/snakemake/test_mini_workflow.py
  tests/test_mavis/annotate/test_annotate.py
  tests/test_mavis/annotate/test_annotate2.py
  tests/test_mavis/annotate/test_annotate_fileio.py
  tests/test_mavis/annotate/test_call_indels.py
  tests/test_mavis/annotate/test_splicing.py
  tests/test_mavis/bam/test_bam.py
  tests/test_mavis/bam/test_cigar.py
  tests/test_mavis/cluster/test_cluster.py
  tests/test_mavis/convert/test_convert.py
  tests/test_mavis/convert/test_tool.py
  tests/test_mavis/convert/test_tools_vcf.py
  tests/test_mavis/illustrate/test_illustrate2.py
  tests/test_mavis/pairing/test_pairing.py
  tests/test_mavis/summary/test_summary.py
  tests/test_mavis/test_align.py
  tests/test_mavis/test_args.py
  tests/test_mavis/test_assemble.py
  tests/test_mavis/test_assemble2.py
  tests/test_mavis/test_bam.py
  tests/test_mavis/test_blat.py
  tests/test_mavis/test_blat2.py
  tests/test_mavis/test_breakpoint.py
  tests/test_mavis/test_breakpoint2.py
  tests/test_mavis/test_constants.py
  tests/test_mavis/test_help.py
  tests/test_mavis/test_interval.py
  tests/test_mavis/test_overlay.py
  tests/test_mavis/test_util.py
  tests/test_mavis/validate/test_call.py
  tests/test_mavis/validate/test_evidence.py
  tests/test_mavis/validate/test_validate2.py
  tests/test_tools/test_convert_annotations_format.py
  tests/test_tools/test_convert_dgv.py
  tests/test_tools/test_ref_alt_count.py
Labels: devops, code-style
