Repository bcgsc/mavis, pull requests merged in 2022-02, with the labels that each got.

#303 Feature/more type annotations
  src/mavis/align.py
  src/mavis/annotate/base.py
  src/mavis/annotate/file_io.py
  src/mavis/annotate/fusion.py
  src/mavis/annotate/genomic.py
  src/mavis/annotate/main.py
  src/mavis/annotate/protein.py
  src/mavis/annotate/variant.py
  src/mavis/assemble.py
  src/mavis/bam/cache.py
  src/mavis/bam/stats.py
  src/mavis/blat.py
  src/mavis/breakpoint.py
  src/mavis/cluster/cluster.py
  src/mavis/constants.py
  src/mavis/illustrate/elements.py
  src/mavis/illustrate/scatter.py
  src/mavis/interval.py
  src/mavis/main.py
  src/mavis/types.py
  src/mavis/util.py
  src/mavis/validate/evidence.py
Labels: documentation, code-style

#300 Feature/sniffle convert handling
  docs/hooks.py
  src/mavis/tools/constants.py
  src/mavis/tools/vcf.py
  tests/data/sniffles.vcf
  tests/end_to_end/test_convert.py
  tests/unit/test_tools_vcf.py
Labels: long read support, SV caller

#306 Feature/gff support
  .github/workflows/build.yml
  docs/inputs/reference.md
  docs/migrating.md
  docs/tutorials/full.md
  setup.cfg
  src/mavis/annotate/annotations_schema.json
  src/mavis/annotate/file_io.py
  src/mavis/annotate/protein.py
  src/mavis/annotate/splicing.py
  src/tools/convert_annotations_format.py
  src/tools/generate_ensembl_json.py
  src/tools/get_hg19_reference_files.sh
  src/tools/get_hg38_reference_files.sh
  src/tools/migrate_mavis_annotations_2to3.py
  tests/data/example_genes.json
  tests/tools/data/Homo_sapiens.GRCh38.kras.gff3
  tests/tools/data/Homo_sapiens.GRCh38.kras.gff3.json
  tests/tools/data/Homo_sapiens.GRCh38.kras.gtf
  tests/tools/data/Homo_sapiens.GRCh38.kras.gtf.json
  tests/tools/data/K02718.1.gff3
  tests/tools/data/K02718.1.gff3.json
  tests/tools/data/K02718.1.gtf
  tests/tools/data/K02718.1.gtf.json
  tests/tools/data/ensembl69_hg19_annotations.kras.tab
  tests/tools/data/ensembl69_hg19_annotations.kras.tab.json
  tests/tools/data/example_genes.v2.json
  tests/tools/data/example_genes.v3.json
  tests/tools/test_convert_annotations_format.py
Labels: enhancement

#309 Feature/fix rtd typo
  .readthedocs.yml
  setup.cfg
Labels: documentation

#311 Make template metadata file optional
  src/mavis/annotate/file_io.py
  src/mavis/annotate/main.py
  tests/mini-tutorial.annotate_only.config.json
Labels: bug

#313 Bugfix/enforce unique tid
  src/tools/convert_annotations_format.py
  tests/data/mock_reference_annotations2.json
  tests/test_tools/data/viral.gtf
  tests/test_tools/data/viral.gtf.json
  tests/test_tools/test_convert_annotations_format.py
Labels: bug
